### PR TITLE
Feb 2024 Sync

### PR DESCRIPTION
**Pull request by tomtaylor**
- Move all records to be parented by `postalregion` (https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/pull/85) where available. Some ceased postcodes never got a postalregion created for them (as the entire region was ceased by the time we created the polygons), so they have moved from being parented by whatever PIP returned, to `-1` with an empty hierarchy. It might be possible to recreate the historical postalregion at some point in the future, but it's not a priority right now.
- Sync with Feb 2024 ONS release

### CODE REVIEW

**Comment by tomtaylor** [comment]
FYI @missinglink

**Comment by missinglink** [comment]
@tomtaylor I noticed that we are no longer getting region information for GB postcodes in Pelias, for instance `454553645` used to be in the region of 'Greater London' and now is not.

Was that the intention? ie. to *replace* the `region` parent with `postalregion` or was the intention to have *both*?

- https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/blame/master/data/454/553/645/454553645.geojson
- https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/blame/ce404edadd3f7a451cb8e047b63bba005c175ec0/data/454/553/645/454553645.geojson

**Comment by missinglink** [comment]
Screenshot 2024-09-25 at 11 59 38

**Comment by missinglink** [comment]
The labels are now `EN5 2LP, United Kingdom`, since we don't have the ~~country~~ macroregion either 🤔

**Comment by missinglink** [comment]
I would be 👍 for adding the previous `hierarchy` entires back in the next GB build, along with the new `postalregion` entries.

Is that something you'd consider?

**Pull request merged**
