### PR TITLE
November 2022 sync

### PR DESCRIPTION
**Pull request by tomtaylor**
First commit to prep, by rePIPing all existing records.

Second commit to update existing features and create new features from the November 2022 data.

### CODE REVIEW

**Comment by tomtaylor** [comment]
Paging @missinglink!

**Comment by missinglink** [comment]
oh is it that time again ⌚ 👀 , only ♾️ files changed, I'll have a look 😉

**Comment by missinglink** [comment]
review method:

```bash
rm -rf /tmp/whosonfirst-data-postalcode-gb
mkdir /tmp/whosonfirst-data-postalcode-gb

git clone \
  --progress \
  --branch repip-august-2022 \
  --depth 3 \
  --single-branch \
  --bare \
  https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb.git \
  /tmp/whosonfirst-data-postalcode-gb

git --git-dir=/tmp/whosonfirst-data-postalcode-gb \
  diff d4519e49fd9ba732710e851ecdd0cc405dc64be3 a4e72aeb38ab97e954627ab4d2a361e4e52d5610
```

**Comment by missinglink** [comment]
this record didn't change geometry but changed locality, seems it's because the record is duplicated in WOF 🤔 

```diff
diff --git a/data/116/071/530/4/1160715304.geojson b/data/116/071/530/4/1160715304.geojs
on
index 2f8726b12dda..ce439d397dec 100644
--- a/data/116/071/530/4/1160715304.geojson
+++ b/data/116/071/530/4/1160715304.geojson
@@ -22,13 +22,13 @@
     "os:region_code": "W99999999",
     "src:geom": "os",
     "wof:belongsto": [
-      1243583119,
       404227475,
       1360698627,
       85633159,
       1360698899,
       404433843,
-      102191581
+      102191581,
+      101750395
     ],
     "wof:breaches": [],
     "wof:country": "GB",
@@ -40,16 +40,16 @@
         "country_id": 85633159,
         "county_id": 1360698899,
         "localadmin_id": 404433843,
-        "locality_id": 1243583119,
+        "locality_id": 101750395,
         "macroregion_id": 404227475,
         "postalcode_id": 1160715304,
         "region_id": 1360698627
       }
     ],
     "wof:id": 1160715304,
-    "wof:lastmodified": 1661974351,
+    "wof:lastmodified": 1673229314,
     "wof:name": "CF6 7LZ",
-    "wof:parent_id": 1243583119,
+    "wof:parent_id": 101750395,
     "wof:placetype": "postalcode",
     "wof:repo": "whosonfirst-data-postalcode-gb",
     "wof:superseded_by": [],
```

- https://spelunker.whosonfirst.org/id/1243583119/
- https://spelunker.whosonfirst.org/id/101750395/

**Comment by missinglink** [comment]
same here:

```diff
diff --git a/data/116/071/633/2/1160716332.geojson b/data/116/071/633/2/1160716332.geojs
on
index 2fba714ebd81..b5cb851225e2 100644
--- a/data/116/071/633/2/1160716332.geojson
+++ b/data/116/071/633/2/1160716332.geojson
@@ -28,7 +28,7 @@
       1360698757,
       1360817173,
       102191581,
-      1259812663
+      101750325
     ],
     "wof:breaches": [],
     "wof:country": "GB",
@@ -40,16 +40,16 @@
         "country_id": 85633159,
         "county_id": 1360698757,
         "localadmin_id": 1360817173,
-        "locality_id": 1259812663,
+        "locality_id": 101750325,
         "macroregion_id": 404227469,
         "postalcode_id": 1160716332,
         "region_id": 1360698607
       }
     ],
     "wof:id": 1160716332,
-    "wof:lastmodified": 1662008384,
+    "wof:lastmodified": 1673229257,
     "wof:name": "BN4 5FX",
-    "wof:parent_id": 1259812663,
+    "wof:parent_id": 101750325,
     "wof:placetype": "postalcode",
     "wof:repo": "whosonfirst-data-postalcode-gb",
     "wof:superseded_by": [],
```

**Comment by missinglink** [comment]
Looks good to me, lots of location changes, deprecations and restorations.

In total there are 56881 changes, it's crazy how many there are in such a short time 🤷‍♂️

**Comment by tomtaylor** [comment]
Great, merging now!

**Pull request merged**
