### PR TITLE
Sync with May 2020 ONS Postcode Directory

### PR DESCRIPTION
**Pull request by tomtaylor**
89970 features updated. 3189 new features created.

The updated features contain some cessations but are mostly centroids that have moved a small distance. I haven't re-pip'd existing the records as it seems unlikely the postcodes will have moved very far.

### CODE REVIEW

**Comment by tomtaylor** [comment]
cc: @stepps00

**Comment by thisisaaronland** [comment]
Can I interest you in writing a blog post about this work?

**Comment by tomtaylor** [comment]
> Can I interest you in writing a blog post about this work?

Sure! I'll try and draft something up...

**Comment by stepps00** [comment]
Thanks @tomtaylor - I'm pulling down the changes to inspect the changes locally.

Did you take the same approach in this PR as you did with the work in https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/4? Assuming the workflows are the same, this should be a quick merge.

**Comment by stepps00** [comment]
An example of a new record being added in this PR:
```
{
  "id": 1713327887,
  "type": "Feature",
  "properties": {
    "edtf:cessation": "uuuu",
    "edtf:inception": "2020-04-01",
    "geom:area": 0,
    "geom:bbox": "-0.538962,53.173228,-0.538962,53.173228",
    "geom:latitude": 53.173228,
    "geom:longitude": -0.538962,
    "iso:country": "GB",
    "mz:hierarchy_label": 1,
    "mz:is_current": 1,
    "os:country_code": "E92000001",
    "os:county_code": "E10000019",
    "os:district_code": "E07000139",
    "os:positional_quality_indicator": "5",
    "os:region_code": "E12000004",
    "src:geom": "os",
    "wof:belongsto": [
      85633159, 
      1360699067, 
      404445475, 
      1360759405, 
      404227469, 
      1360698571
    ],
    "wof:breaches": [],
    "wof:country": "GB",
    "wof:created": 1595735505,
    "wof:geomhash": "1bf7e8ac3848bc04c5d8d076b5dd8122",
    "wof:hierarchy": [
      {
        "country_id": 85633159,
        "county_id": 1360699067,
        "localadmin_id": 404445475,
        "locality_id": 1360759405,
        "macroregion_id": 404227469,
        "region_id": 1360698571
      }
    ],
    "wof:id": 1713327887,
    "wof:lastmodified": 1595753346,
    "wof:name": "LN5 9ZD",
    "wof:parent_id": -1,
    "wof:placetype": "postalcode",
    "wof:repo": "whosonfirst-data-postalcode-gb",
    "wof:superseded_by": [],
    "wof:supersedes": [],
    "wof:tags": []
  },
  "bbox": [
    -0.538962, 
    53.173228, 
    -0.538962, 
    53.173228
  ],
  "geometry": {"coordinates":[-0.538962,53.173228],"type":"Point"}
}
```

Overall, I don't see any issues that would prevent this from being merged.. just a few questions/comments, some of which were already clarified in #4.. but I want to confirm.

- The formatting/spacing seems similar to the edits in #4, which differ a bit from the Python `wof-exportify` tool, and come from the Go versions of this tool. Was the Go export tool run against each new/edited record in this PR?
- The `wof:id` integers on new records look like they're sourced from Brooklyn Integers.. is that true?
- I don't think re-PIPing these records is a requirement to get this merged.. but curious if you think this would be a useful followup.

**Comment by tomtaylor** [comment]
> * The formatting/spacing seems similar to the edits in #4, which differ a bit from the Python `wof-exportify` tool, and come from the Go versions of this tool. Was the Go export tool run against each new/edited record in this PR?

That's right - all these changes are generated using [wof-sync-os-postcodes](https://github.com/whosonfirst/wof-sync-os-postcodes), which uses the Go export/format libraries.

> * The `wof:id` integers on new records look like they're sourced from Brooklyn Integers.. is that true?

That's right - I updated `wof-sync-os-postcodes` to only use Brooklyn integers, as per the feedback on #4.

> * I don't think re-PIPing these records is a requirement to get this merged.. but curious if you think this would be a useful followup.

I think the centroids have typically moved an incredibly small amount, and it's unlikely many records have moved enough to change the hierarchy. But it can't hurt! It's just a flag on `wof-sync-os-postcodes` now. Happy to follow up with another PR.

**Comment by stepps00** [comment]
> I think the centroids have typically moved an incredibly small amount, and it's unlikely many records have moved enough to change the hierarchy. But it can't hurt! It's just a flag on wof-sync-os-postcodes now. Happy to follow up with another PR.

I think it would be helpful for these new records to gain updated hierarchies when applicable, but more importantly, PIPing these records would give these records new `wof:parent_id` values.

This looks good to me -- unless there is anything else to add, I'll get this merged today. Thanks for the contribution!

**Comment by tomtaylor** [comment]
No problem, thanks for reviewing!

**Comment by stepps00** [comment]
Paging @nvkelso - lots of great updates to the GB postalcodes here.

**Comment by stepps00** [comment]
I gave the changes another look and I think this is ready to ship. I'll add a follow-up issue to the main wof-data repo to track PIP updates to these records and link this PR.

Thanks again @tomtaylor

**Comment by missinglink** [comment]
Hi guys, the May 2021 ONS file came out recently, is it relatively easier to sync the new files since this PR landed?
If so, would it be worth updating?

https://geoportal.statistics.gov.uk/datasets/7b543e410eb74fa6a4690346222782fc/about

**Pull request merged**
