### PR TITLE
August 2021 sync

### PR DESCRIPTION
**Pull request by tomtaylor**
Merge this after #6. This updates the repo against the August 2021 sync. It updates 135,928 features and creates 21,449 new features.

### CODE REVIEW

**Comment by tomtaylor** [comment]
OK, I've rebased this with a single commit which syncs against August 2021 using the same code as #6. After this, let's do August 2022!

**Comment by tomtaylor** [comment]
cc @missinglink

**Comment by missinglink** [comment]
Looking at [WS13 8WL](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-postalcode-gb/master/data/116/071/311/4/1160713114.geojson) I can see that it's back from the dead: `mz:is_current: 0 -> mz:is_current: 1`

Is this expected? ie. Do postcodes get retired and then reanimated?

```diff
diff --git a/data/116/071/311/4/1160713114.geojson b/data/116/071/311/4/1160713114.geojson
index 7399094fc081..1c46ccf577c4 100644
--- a/data/116/071/311/4/1160713114.geojson
+++ b/data/116/071/311/4/1160713114.geojson
@@ -2,19 +2,17 @@
   "id": 1160713114,
   "type": "Feature",
   "properties": {
-    "date:cessation_lower": "2020-02-01",
-    "date:cessation_upper": "2020-02-01",
-    "date:inception_lower": "2020-01-01",
-    "date:inception_upper": "2020-01-01",
-    "edtf:cessation": "2020-02-01",
-    "edtf:inception": "2020-01-01",
+    "date:inception_lower": "2021-01-01",
+    "date:inception_upper": "2021-01-01",
+    "edtf:cessation": "",
+    "edtf:inception": "2021-01-01",
     "geom:area": 0,
-    "geom:bbox": "-1.800795,52.694174,-1.800795,52.694174",
-    "geom:latitude": 52.694174,
-    "geom:longitude": -1.800795,
+    "geom:bbox": "-1.800957,52.694336,-1.800957,52.694336",
+    "geom:latitude": 52.694336,
+    "geom:longitude": -1.800957,
     "iso:country": "GB",
     "mz:hierarchy_label": 1,
-    "mz:is_current": 0,
+    "mz:is_current": 1,
     "os:country_code": "E92000001",
     "os:county_code": "E10000028",
     "os:district_code": "E07000194",
@@ -33,7 +31,7 @@
     "wof:breaches": [],
     "wof:country": "GB",
     "wof:created": 1583786923,
-    "wof:geomhash": "76fd71d2bd091698781b38dba9c9677f",
+    "wof:geomhash": "740bffeb14a890b6b350e950eee9c7a0",
     "wof:hierarchy": [
       {
         "continent_id": 102191581,
@@ -47,7 +45,7 @@
       }
     ],
     "wof:id": 1160713114,
-    "wof:lastmodified": 1661974367,
+    "wof:lastmodified": 1662029356,
     "wof:name": "WS13 8WL",
     "wof:parent_id": 1360756223,
     "wof:placetype": "postalcode",
@@ -57,10 +55,10 @@
     "wof:tags": []
   },
   "bbox": [
-    -1.800795,
-    52.694174,
-    -1.800795,
-    52.694174
+    -1.800957,
+    52.694336,
+    -1.800957,
+    52.694336
   ],
-  "geometry": {"coordinates":[-1.800795,52.694174],"type":"Point"}
+  "geometry": {"coordinates":[-1.800957,52.694336],"type":"Point"}
 }
```

**Comment by missinglink** [comment]
Another example of the same class of change `KA3 3FG`

```diff
diff --git a/data/116/071/320/8/1160713208.geojson b/data/116/071/320/8/1160713208.geojson
index c58c25877e97..f6d2ecea4b23 100644
index c58c25877e97..f6d2ecea4b23 100644
--- a/data/116/071/320/8/1160713208.geojson
+++ b/data/116/071/320/8/1160713208.geojson
@@ -2,23 +2,21 @@
   "id": 1160713208,
   "type": "Feature",
   "properties": {
-    "date:cessation_lower": "2018-02-01",
-    "date:cessation_upper": "2018-02-01",
-    "date:inception_lower": "2018-01-01",
-    "date:inception_upper": "2018-01-01",
-    "edtf:cessation": "2018-02-01",
-    "edtf:inception": "2018-01-01",
+    "date:inception_lower": "2020-06-01",
+    "date:inception_upper": "2020-06-01",
+    "edtf:cessation": "",
+    "edtf:inception": "2020-06-01",
     "geom:area": 0,
-    "geom:bbox": "-4.523516,55.686891,-4.523516,55.686891",
-    "geom:latitude": 55.686891,
-    "geom:longitude": -4.523516,
+    "geom:bbox": "-4.526845,55.685716,-4.526845,55.685716",
+    "geom:latitude": 55.685716,
+    "geom:longitude": -4.526845,
     "iso:country": "GB",
     "mz:hierarchy_label": 1,
-    "mz:is_current": 0,
+    "mz:is_current": 1,
     "os:country_code": "S92000003",
     "os:county_code": "S99999999",
     "os:district_code": "S12000008",
-    "os:positional_quality_indicator": "5",
+    "os:positional_quality_indicator": "2",
     "os:region_code": "S99999999",
     "src:geom": "os",
     "wof:belongsto": [
@@ -32,7 +30,7 @@
     "wof:breaches": [],
     "wof:country": "GB",
     "wof:created": 1583786923,
-    "wof:geomhash": "308ea606c85de8f016fa862198fa91e9",
+    "wof:geomhash": "e260a35e30c231046cbf85761fdd5b6a",
     "wof:hierarchy": [
       {
         "continent_id": 102191581,
@@ -45,7 +43,7 @@
       }
     ],
     "wof:id": 1160713208,
-    "wof:lastmodified": 1661974366,
+    "wof:lastmodified": 1662029356,
     "wof:name": "KA3 3FG",
     "wof:parent_id": 404451413,
     "wof:placetype": "postalcode",
@@ -55,10 +53,10 @@
     "wof:tags": []
   },
   "bbox": [
-    -4.523516,
-    55.686891,
-    -4.523516,
-    55.686891
+    -4.526845,
+    55.685716,
+    -4.526845,
+    55.685716
   ],
-  "geometry": {"coordinates":[-4.523516,55.686891],"type":"Point"}
+  "geometry": {"coordinates":[-4.526845,55.685716],"type":"Point"}
 }
```

**Comment by missinglink** [comment]
noteworthy but probably fine:

```diff
diff --git a/data/116/071/653/8/1160716538.geojson b/data/116/071/653/8/1160716538.geojson
index 1191163fda04..e18d798de68e 100644
--- a/data/116/071/653/8/1160716538.geojson
+++ b/data/116/071/653/8/1160716538.geojson
@@ -16,8 +16,8 @@
     "mz:hierarchy_label": 1,
     "mz:is_current": 0,
     "os:country_code": "E92000001",
-    "os:county_code": "E10000021",
-    "os:district_code": "E07000154",
+    "os:county_code": "E99999999",
+    "os:district_code": "E06000062",
     "os:positional_quality_indicator": "1",
     "os:region_code": "E12000004",
     "src:geom": "os",
@@ -45,7 +45,7 @@
       }
     ],
     "wof:id": 1160716538,
-    "wof:lastmodified": 1661974339,
+    "wof:lastmodified": 1662029356,
     "wof:name": "NN3 1DZ",
     "wof:parent_id": 101750459,
     "wof:placetype": "postalcode",
 ```

**Comment by missinglink** [comment]
So yeah, it's lots of minor lat/lon changes and some codes being retired and some being reinstated, looks good to me.
Just a question about whether it's legitimate that codes come back from the dead, if that's true then this looks good to me.

**Comment by tomtaylor** [comment]
So, yeah, they do seem to get reinstated, for example when a housing block is demolished, and another rebuilt nearby. They'd only be reused in the same local area. I think technically this should be supported by ceasing the old one and creating a new record, but that's more work that I haven't done yet...

**Comment by missinglink** [comment]
If it's a reflection of the real-world and not a tooling error then I'm 👍 for merging this.

**Comment by tomtaylor** [comment]
Hurrah!

**Comment by missinglink** [comment]
Screenshot 2022-09-02 at 10 57 41

**Pull request merged**
